name: release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag version"
        required: true

env:
  VERSION: ${{ github.event.inputs.version }}

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: git config
        run: |
          git config --global user.name ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'tronto20' }}
          git config --global user.email "${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'tronto20' }}@noreply.github.com"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: version
        run: npm version "${{ env.VERSION }}"

      - name: build
        run: npm run build

      - name: git versioning
        run: |
          git tag --list
          git remote -v
          git push
          git push origin v${{ env.VERSION }}

      - name: release to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Tag and Release
        uses: ncipollo/release-action@v1
        id: core_tag_and_release
        with:
          tag: v${{ env.VERSION }}
          name: 'v${{ env.VERSION }}'
          generateReleaseNotes: true
          prerelease: false
          draft: false
          artifacts: 'dist/*'